name: website CI
on:
    push:
        branches: [main]

jobs:
    build: 
        runs-on: self-hosted
        steps:
        -   uses: actions/checkout@v2
        -   name: setup node
            uses: actions/setup-node@v1
            with:
                node-version: 14
        -   run: |
                npm i
                npm run build
            


            
