name: website CI
on:
    push:
        branches: [main]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: setup node
            uses: actions/setup-node@v2
            with:
                node-version: '18'
        -   name: build
            run: |
                npm install
                npm run build
        -   name: Copy dist to VPS
            uses: appleboy/scp-action@master
            with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: ".,!node_modules"
                  target: "/var/www/test.com"
                
        # -   name: setup ssh
        #     env:
        #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #         SSH_HOST: ${{ secrets.SSH_HOST }}
        #         SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        #     run: |
        #         echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        #         ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USERNAME}@${SSH_HOST}  "
        #         echo SSH connection established
        #         cd /var/www/test.com
        #         git pull
        #         sudo npm cache clean -f
        #         sudo npm install -g n
        #         sudo n stable
        #         node -v
        #         npm i
        #         npm run build
        #         pm2 stop 0
        #         pm2 start 0
        #         pm2 save
        #         sudo /usr/sbin/service nginx restart
        #         "
    

                
            


            
