name: website CI
on:
    push:
        branches: [main]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: setup ssh
            env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                SSH_HOST: ${{ secrets.SSH_HOST }}
                SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
            run: |
                echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
                ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USERNAME}@${SSH_HOST}  "echo SSH connection established"
                cd /var/www/test.com
                git pull
    

                

                
        -   name: setup node
            uses: actions/setup-node@v1
            with:
                node-version: 14
        -   run: |
                npm i
                npm run build
                pm2 stop 0
                pm2 start 0
                pm2 save
                sudo /usr/sbin/service nginx restart
            


            
