name: website CI
on:
    push:
        branches: [main]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: setup node
            uses: actions/setup-node@v2
            with:
                node-version: '18'
        -   name: build
            run: |
                npm install
                npm run build
        -   name: Copy dist to VPS
            uses: appleboy/scp-action@master
            with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: ".,!node_modules"
                  target: "/var/www/test.com"
        -   name: SSH Commands deploy
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    cd /var/www/test.com
                    npm install --omit=dev
                    pm2 stop 0
                    pm2 start 0
                    pm2 save
                    sudo /usr/sbin/service nginx restart
                
  